#ifndef YDWE_VERSION_H_INCLUDED
#define YDWE_VERSION_H_INCLUDED

#define YDWE_VERSION_MAJOR 1
#define YDWE_VERSION_MINOR 30
#define YDWE_VERSION_REVISED 6
#define YDWE_VERSION_BUILD 233

#endif // YDWE_VERSION_H_INCLUDED
