
#define WMSaveBoolean(p,c,b) SaveBoolean(WMHT,p,c,b)
#define WMSaveInteger(p,c,i) SaveInteger(WMHT,p,c,i)
#define WMSaveReal(p,c,r) SaveReal(WMHT,p,c,r)
#define WMSaveUnitHandle(p,c,u) SaveUnitHandle(WMHT,p,c,u)
#define WMSaveStr(p,c,s) SaveStr(WMHT,p,c,s)
#define WMSaveTriggerHandle(p,c,tri) SaveTriggerHandle(WMHT,p,c,tri)
#define WMSaveDestructableHandle(p,c,d) SaveDestructableHandle(WMHT,p,c,d)
#define WMSaveGroupHandle(p,c,g) SaveGroupHandle(WMHT,p,c,g)
#define WMLoadGroupHandle(p,c) LoadGroupHandle(WMHT,p,c)
#define WMLoadTriggerHandle(p,c) LoadTriggerHandle(WMHT,p,c)
#define WMLoadStr(p,c) LoadStr(WMHT,p,c)
#define WMLoadUnitHandle(p,c) LoadUnitHandle(WMHT,p,c)
#define WMLoadReal(p,c) LoadReal(WMHT,p,c)
#define WMLoadInteger(p,c) LoadInteger(WMHT,p,c)
#define WMLoadBoolean(p,c) LoadBoolean(WMHT,p,c)
#define WMFlushChildHashtable(p) FlushChildHashtable(WMHT,p)
#define WMLoadDestructableHandle(p,c) LoadDestructableHandle(WMHT,p,c)
